# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbindARMA <- function(A, B) {
    .Call('myFunctions_cbindARMA', PACKAGE = 'myFunctions', A, B)
}

colSums <- function(X) {
    .Call('myFunctions_colSums', PACKAGE = 'myFunctions', X)
}

convertToAlpha <- function(mu, s2) {
    .Call('myFunctions_convertToAlpha', PACKAGE = 'myFunctions', mu, s2)
}

convertToBeta <- function(mu, s2) {
    .Call('myFunctions_convertToBeta', PACKAGE = 'myFunctions', mu, s2)
}

dinvgammaArma <- function(x, shape, rate, logarithm = TRUE) {
    .Call('myFunctions_dinvgammaArma', PACKAGE = 'myFunctions', x, shape, rate, logarithm)
}

dinvgammaArmaVec <- function(x, shape, rate, logarithm = TRUE) {
    .Call('myFunctions_dinvgammaArmaVec', PACKAGE = 'myFunctions', x, shape, rate, logarithm)
}

dMVNorm <- function(y, mu, Sig) {
    .Call('myFunctions_dMVNorm', PACKAGE = 'myFunctions', y, mu, Sig)
}

dmvnormArmaVec <- function(x, mean, Sigma, logd = FALSE) {
    .Call('myFunctions_dmvnormArmaVec', PACKAGE = 'myFunctions', x, mean, Sigma, logd)
}

phi <- function(x) {
    .Call('myFunctions_phi', PACKAGE = 'myFunctions', x)
}

logDet <- function(Sig) {
    .Call('myFunctions_logDet', PACKAGE = 'myFunctions', Sig)
}

makeDistARMA <- function(coords1, coords2) {
    .Call('myFunctions_makeDistARMA', PACKAGE = 'myFunctions', coords1, coords2)
}

makePCA <- function(X) {
    .Call('myFunctions_makePCA', PACKAGE = 'myFunctions', X)
}

mvrnormArma <- function(n, mu, Sigma) {
    .Call('myFunctions_mvrnormArma', PACKAGE = 'myFunctions', n, mu, Sigma)
}

mvrnormArmaVec <- function(mu, Sigma) {
    .Call('myFunctions_mvrnormArmaVec', PACKAGE = 'myFunctions', mu, Sigma)
}

orderArma <- function(x) {
    .Call('myFunctions_orderArma', PACKAGE = 'myFunctions', x)
}

rbindARMA <- function(A, B) {
    .Call('myFunctions_rbindARMA', PACKAGE = 'myFunctions', A, B)
}

rMVNArma <- function(A, b) {
    .Call('myFunctions_rMVNArma', PACKAGE = 'myFunctions', A, b)
}

rMVNArmaScalar <- function(a, b) {
    .Call('myFunctions_rMVNArmaScalar', PACKAGE = 'myFunctions', a, b)
}

rowMeans <- function(X) {
    .Call('myFunctions_rowMeans', PACKAGE = 'myFunctions', X)
}

rowSds <- function(X) {
    .Call('myFunctions_rowSds', PACKAGE = 'myFunctions', X)
}

rowSums <- function(X) {
    .Call('myFunctions_rowSums', PACKAGE = 'myFunctions', X)
}

svdARMA <- function(X) {
    .Call('myFunctions_svdARMA', PACKAGE = 'myFunctions', X)
}

dcsvdARMA <- function(X) {
    .Call('myFunctions_dcsvdARMA', PACKAGE = 'myFunctions', X)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('myFunctions_RcppExport_registerCCallable', PACKAGE = 'myFunctions')
})
